#!/bin/bash

function start()
{
	if ! grep -q "pi_observe" /etc/rc.local; then
		sed -ri '/^exit 0/i\/usr/local/bin/pi_observe' /etc/rc.local
	fi

	echo "ds1307 0x68" > /sys/class/i2c-adapter/i2c-1/new_device 2> /dev/null
	/usr/local/bin/set_time_gps.py

	if [ $? == "0" ]; then
		echo "`date`: time set from GPS" >> /var/log/pi_observer/rtc_log
		hwclock -w
	else
		echo "`date`: time set from RTC" >> /var/log/pi_observer/rtc_log
		hwclock -s
	fi

	if ! crontab -l | grep -q "temp_logger.py"; then
		(echo '* * * * * temp_logger.py'; crontab -l) | crontab -
	fi
	if ! crontab -l | grep -q "press_alt_logger.py"; then
		(echo '* * * * * press_alt_logger.py'; crontab -l) | crontab -
	fi
	if ! crontab -l | grep -q "hum_logger.py"; then
		(echo '* * * * * hum_logger.py'; crontab -l) | crontab -
	fi
	if ! crontab -l | grep -q "location_logger.py"; then
		(echo '* * * * * location_logger.py'; crontab -l) | crontab -
	fi
	if ! crontab -l | grep -q "chart_drawer.py"; then
		(echo '*/30 * * * * chart_drawer.py'; crontab -l) | crontab -
	fi
}

function stop()
{
	sed -i '/pi_observe/d' /etc/rc.local

	crontab -l | grep -v 'temp_logger.py' | crontab
	crontab -l | grep -v 'press_alt_logger.py' | crontab
	crontab -l | grep -v 'hum_logger.py' | crontab
	crontab -l | grep -v 'location_logger.py' | crontab
	crontab -l | grep -v 'chart_drawer.py' | crontab
}

if [ "$(id -u)" != 0 ]; then
	echo "Start script must be run with root permissions" 
	exit 1
fi

case $1 in
	stop)
		stop
		exit
		;;
	*)
		start
		;;
esac

